[2024-07-13T10:50:33.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T10:50:33.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-04-13T00:00:00+00:00 [queued]>
[2024-07-13T10:50:33.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-04-13T00:00:00+00:00 [queued]>
[2024-07-13T10:50:33.214+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-13T10:50:33.230+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): build_image> on 2023-04-13 00:00:00+00:00
[2024-07-13T10:50:33.238+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T10:50:33.239+0000] {standard_task_runner.py:63} INFO - Started process 374 to run task
[2024-07-13T10:50:33.239+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'deploy_flask_app', 'build_image', 'scheduled__2023-04-13T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/deploy_flask_app.py', '--cfg-path', '/tmp/tmpji72kxbz']
[2024-07-13T10:50:33.241+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask build_image
[2024-07-13T10:50:33.285+0000] {task_command.py:426} INFO - Running <TaskInstance: deploy_flask_app.build_image scheduled__2023-04-13T00:00:00+00:00 [running]> on host e9ee640206e7
[2024-07-13T10:50:33.367+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_flask_app' AIRFLOW_CTX_TASK_ID='build_image' AIRFLOW_CTX_EXECUTION_DATE='2023-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-13T00:00:00+00:00'
[2024-07-13T10:50:33.368+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T10:50:33.370+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-13T10:50:33.371+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker build -t my-flask-app .']
[2024-07-13T10:50:33.388+0000] {subprocess.py:86} INFO - Output:
[2024-07-13T10:50:33.411+0000] {subprocess.py:93} INFO - DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
[2024-07-13T10:50:33.412+0000] {subprocess.py:93} INFO -             Install the buildx component to build images with BuildKit:
[2024-07-13T10:50:33.413+0000] {subprocess.py:93} INFO -             https://docs.docker.com/go/buildx/
[2024-07-13T10:50:33.413+0000] {subprocess.py:93} INFO - 
[2024-07-13T10:50:33.414+0000] {subprocess.py:93} INFO - unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/***tmpxll11grm/Dockerfile: no such file or directory
[2024-07-13T10:50:33.414+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-13T10:50:33.415+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T10:50:33.423+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-13T10:50:33.427+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_flask_app, task_id=build_image, run_id=scheduled__2023-04-13T00:00:00+00:00, execution_date=20230413T000000, start_date=20240713T105033, end_date=20240713T105033
[2024-07-13T10:50:33.439+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task build_image (Bash command failed. The command returned a non-zero exit code 1.; 374)
[2024-07-13T10:50:33.454+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T10:50:33.473+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T10:50:33.476+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
