[2024-07-13T10:56:04.470+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T10:56:04.551+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-04-12T00:00:00+00:00 [queued]>
[2024-07-13T10:56:04.569+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-04-12T00:00:00+00:00 [queued]>
[2024-07-13T10:56:04.579+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-13T10:56:04.610+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): build_image> on 2023-04-12 00:00:00+00:00
[2024-07-13T10:56:04.625+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=545) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T10:56:04.631+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'deploy_flask_app', 'build_image', 'scheduled__2023-04-12T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/deploy_flask_app.py', '--cfg-path', '/tmp/tmp6jyxyj38']
[2024-07-13T10:56:04.639+0000] {standard_task_runner.py:63} INFO - Started process 586 to run task
[2024-07-13T10:56:04.639+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask build_image
[2024-07-13T10:56:04.761+0000] {task_command.py:426} INFO - Running <TaskInstance: deploy_flask_app.build_image scheduled__2023-04-12T00:00:00+00:00 [running]> on host e9ee640206e7
[2024-07-13T10:56:04.992+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_flask_app' AIRFLOW_CTX_TASK_ID='build_image' AIRFLOW_CTX_EXECUTION_DATE='2023-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-12T00:00:00+00:00'
[2024-07-13T10:56:05.001+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T10:56:05.004+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-13T10:56:05.007+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker build -t my-flask-app .']
[2024-07-13T10:56:05.129+0000] {subprocess.py:86} INFO - Output:
[2024-07-13T10:56:05.885+0000] {subprocess.py:93} INFO - DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
[2024-07-13T10:56:05.889+0000] {subprocess.py:93} INFO -             Install the buildx component to build images with BuildKit:
[2024-07-13T10:56:05.890+0000] {subprocess.py:93} INFO -             https://docs.docker.com/go/buildx/
[2024-07-13T10:56:05.893+0000] {subprocess.py:93} INFO - 
[2024-07-13T10:56:05.907+0000] {subprocess.py:93} INFO - unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/***tmpdi_tnkl1/Dockerfile: no such file or directory
[2024-07-13T10:56:05.912+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-13T10:56:05.915+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T10:56:05.976+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-13T10:56:06.028+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=deploy_flask_app, task_id=build_image, run_id=scheduled__2023-04-12T00:00:00+00:00, execution_date=20230412T000000, start_date=20240713T105604, end_date=20240713T105606
[2024-07-13T10:56:06.121+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 91 for task build_image (Bash command failed. The command returned a non-zero exit code 1.; 586)
[2024-07-13T10:56:06.223+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T10:56:06.321+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T10:56:06.349+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
