[2024-07-13T10:49:18.291+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T10:49:18.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2024-07-13T10:49:18.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2024-07-13T10:49:18.444+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-13T10:49:18.510+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): build_image> on 2023-03-25 00:00:00+00:00
[2024-07-13T10:49:18.538+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T10:49:18.543+0000] {standard_task_runner.py:63} INFO - Started process 292 to run task
[2024-07-13T10:49:18.565+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'deploy_flask_app', 'build_image', 'scheduled__2023-03-25T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/deploy_flask_app.py', '--cfg-path', '/tmp/tmp1szet7qr']
[2024-07-13T10:49:18.573+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask build_image
[2024-07-13T10:49:24.840+0000] {task_command.py:426} INFO - Running <TaskInstance: deploy_flask_app.build_image scheduled__2023-03-25T00:00:00+00:00 [running]> on host e9ee640206e7
[2024-07-13T10:49:25.032+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_flask_app' AIRFLOW_CTX_TASK_ID='build_image' AIRFLOW_CTX_EXECUTION_DATE='2023-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-25T00:00:00+00:00'
[2024-07-13T10:49:25.035+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T10:49:25.074+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-13T10:49:25.087+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker build -t my-flask-app .']
[2024-07-13T10:49:25.150+0000] {subprocess.py:86} INFO - Output:
[2024-07-13T10:49:25.561+0000] {subprocess.py:93} INFO - DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
[2024-07-13T10:49:25.562+0000] {subprocess.py:93} INFO -             Install the buildx component to build images with BuildKit:
[2024-07-13T10:49:25.564+0000] {subprocess.py:93} INFO -             https://docs.docker.com/go/buildx/
[2024-07-13T10:49:25.564+0000] {subprocess.py:93} INFO - 
[2024-07-13T10:49:25.568+0000] {subprocess.py:93} INFO - unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/***tmpssojb3zo/Dockerfile: no such file or directory
[2024-07-13T10:49:25.571+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-13T10:49:25.578+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T10:49:25.790+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-13T10:49:25.816+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=deploy_flask_app, task_id=build_image, run_id=scheduled__2023-03-25T00:00:00+00:00, execution_date=20230325T000000, start_date=20240713T104918, end_date=20240713T104925
[2024-07-13T10:49:25.913+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task build_image (Bash command failed. The command returned a non-zero exit code 1.; 292)
[2024-07-13T10:49:25.964+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
